name: build vehicle and publish Docker image to ghcr.io

concurrency: production # allow maximum of one running and pending job

on:
  push:
    paths:
      - 'vehicle/**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-vehicle-and-docker-publish:
    name: Build vehicle
    runs-on: ubuntu-24.04
    env:
      REPOSITORY: 'HikariTempest/vehicle'
      JAVA_VERSION: '21'
      JAVA_DISTRIBUTION: 'temurin'
      DOCKERFILE_LOCATION: './vehicle/target/Dockerfile'
      IMAGE_TAG: 'latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build vehicle project with maven
        working-directory: ./vehicle
        run: | # multi line string operator
          mvn clean package
          cp ./src/main/docker/Dockerfile ./target

      - name: check Dockerfile
        working-directory: ./vehicle/target
        run: dir

      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@v9
        with:
          # every will be "lowercased" internally
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ env.IMAGE_TAG }}
          dockerfile: ${{ env.DOCKERFILE_LOCATION }}

