name: build vehicle and publish Docker image to ghcr.io

concurrency: production # allow maximum of one running and pending job

on:
  push:
    paths:
      - 'vehicle/**'
      - '.github/workflows/build.yaml'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-vehicle-and-docker-publish:
    name: Build vehicle
    runs-on: ubuntu-24.04
    env:
      JAVA_VERSION: '21'
      JAVA_DISTRIBUTION: 'temurin'
      DOCKERFILE_LOCATION: './vehicle/target/'
      IMAGE_TAG: 'latest'
      REPOSITORY: 'HikariTempest/01-referate-HikariTempest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build vehicle project with maven
        working-directory: ./vehicle
        run: | # multi line string operator
          mvn clean package
          cp ./src/main/docker/Dockerfile ./target

      - name: check Dockerfile
        working-directory: ./vehicle/target
        run: dir

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and publish Docker image
        run: |
          REPOSITORY=$(echo '${{ env.REPOSITORY }}' | tr '[:upper:]' '[:lower:]')

          docker build --tag ghcr.io/$REPOSITORY:${{ env.IMAGE_TAG }} ${{ env.DOCKERFILE_LOCATION }}

          docker push ghcr.io/$REPOSITORY:${{ env.IMAGE_TAG }}
          
