name: test github actions

on:
  push:
    paths:
      - '.github/workflows/test.yaml'
  workflow_dispatch:

jobs:
  test:
    name: test github actions
    runs-on: ubuntu-24.04

    steps:
      - name: github repository
        run: echo ${{ github.repository }}
      - name: github sha
        run: echo ${{ github.sha }}
      - name: github event name
        run: echo ${{ github.event_name }}
      - name: github actor
        run: echo ${{ github.actor }}
      - name: github workflow
        run: echo ${{ github.workflow }}
      - name: github run id
        run: echo ${{ github.run_id }}
      - name: github ref
        run: echo ${{ github.ref }}