name: test github actions

on:
  workflow_dispatch:

jobs:
  test:
    name: test github actions
    runs-on: ubuntu-24.04
    env:
      JAVA_VERSION: '21'
      JAVA_DISTRIBUTION: 'temurin'
      RUNNER_JAR_LOCATION: './target'
      PROJECT_LOCATION: './vehicle/'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build vehicle project with maven
        working-directory: ${{ env.PROJECT_LOCATION }}
        run: |
          mvn clean package
          dir ${{ env.RUNNER_JAR_LOCATION }}

      - run: echo ${{ github.GITHUB_REPOSITORY }}
      - run: echo ${{ github.GITHUB_SHA }}
      - run: echo ${{ github.GITHUB_EVENT_NAME }}
      - run: echo ${{ github.GITHUB_ACTOR }}
      - run: echo ${{ github.GITHUB_AUTHOR }}
      - run: echo ${{ github.GITHUB_WORKFLOW }}
      - run: echo ${{ github.GITHUB_RUN_ID }}
      - run: echo ${{ github.GITHUB_REF }}