name: test github actions

on:
  push:
    paths:
      - '.github/workflows/test.yaml'
  workflow_dispatch:

jobs:
  test:
    name: test github actions
    runs-on: ubuntu-24.04

    steps:
      - name: github repository
        run: echo "$GITHUB_REPOSITORY"
      - name: github sha
        run: echo "$GITHUB_SHA"
      - name: github event name
        run: echo "$GITHUB_EVENT_NAME"
      - name: github actor
        run: echo "$GITHUB_ACTOR"
      - name: github author
        run: echo "$GITHUB_AUTHOR"
      - name: github workflow
        run: echo "$GITHUB_WORKFLOW"
      - name: github run id
        run: echo "$GITHUB_RUN_ID"
      - name: github ref
        run: echo "$GITHUB_REF"