name: test github actions

on:
  push:
    paths:
      - '.github/workflows/test.yaml'
  workflow_dispatch:

jobs:
  test:
    name: test github actions
    runs-on: ubuntu-24.04

    steps:
      - name: github repository
        run: echo $GITHUB_REPOSITORY
      - name: github sha
        run: echo $GITHUB_SHA
      - name: github event name
        run: echo $github.GITHUB_EVENT_NAME
      - name: github actor
        run: echo $github.GITHUB_ACTOR
      - name: github author
        run: echo $github.GITHUB_AUTHOR
      - name: github workflow
        run: echo $github.GITHUB_WORKFLOW
      - name: github run id
        run: echo $github.GITHUB_RUN_ID
      - name: github ref
        run: echo $github.GITHUB_REF